Removing databricks run command to test deployment

diff --git a/azure-pipelines_sbox_build.yml b/azure-pipelines_sbox_build.yml
--- a/azure-pipelines_sbox_build.yml
+++ b/azure-pipelines_sbox_build.yml
@@ -111,14 +111,14 @@ stages:
         databricks bundle validate -t sandbox
         databricks bundle deploy -t sandbox
 
-        if [ $? -eq 0 ]; then
-          echo "Deploy successful, waiting 10 seconds before running..."
-          sleep 10
-          databricks bundle run resources/pipelines/ARIA_ARCHIVE_BAILS.yml -t sandbox
-        else
-          echo "Deploy failed"
-          exit 1
-        fi
+#        if [ $? -eq 0 ]; then
+#          echo "Deploy successful, waiting 10 seconds before running..."
+#          sleep 10
+#          databricks bundle run resources/pipelines/ARIA_ARCHIVE_BAILS.yml -t sandbox
+#        else
+#          echo "Deploy failed"
+#          exit 1
+#        fi
       displayName: "Deploy Databricks resources to ingest02 workspace"
 
 #    - script: |
